esphome:
  name: display
  friendly_name: esphome
  name_add_mac_suffix: true

esp32:
  board: m5stack-core-esp32

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}
captive_portal:

web_server:
  port: 80
  version: 3

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

logger:
  level: DEBUG

sensor:
  - platform: homeassistant
    id: ha_climate
    name: "Temperature Sensor From Home Assistant"
    entity_id: climate.wohnzimmer

# inputs
binary_sensor:
  - platform: gpio
    id: button1
    name: "Button up"
    pin:
      number: GPIO39
      inverted: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      - display_menu.up: my_graphical_display_menu

  - platform: gpio
    id: button2
    name: "Button middle"
    pin:
      number: GPIO38
      inverted: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      - if:
          condition:
            display_menu.is_active: my_graphical_display_menu
          then:
            - display_menu.enter: my_graphical_display_menu
          else:
            - display_menu.show: my_graphical_display_menu

  - platform: gpio
    id: button3
    name: "Button down"
    pin:
      number: GPIO37
      inverted: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      - display_menu.down: my_graphical_display_menu

output:
  - platform: ledc
    id: backlight
    pin:
      number: GPIO32
light:
  - platform: monochromatic
    output: backlight
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
display:
  - platform: ili9xxx
    id: my_display
    model: M5Stack
    cs_pin: GPIO14
    dc_pin: GPIO27
    reset_pin: GPIO33
    dimensions:
      height: 240
      width: 320
#    pages:
#      - id: graph_page
#        lambda: |-
#          it.printf(1, 1, id(roboto), "%s", id(ha_climate).state);

graphical_display_menu:
  id: my_graphical_display_menu
  display: my_display
  font: roboto
  on_redraw:
    then:
      component.update: my_display
  active: false
  items:
    - type: Label
      text: Menu Item 1
    - type: Label
      text: Menu Item 2

font:
  - file: "gfonts://Roboto"
    id: roboto
