esphome:
    name: esplight
    project:
      name: esplight.esphome
      version: "1.0"
  
esp8266:
  board: nodemcuv2

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

web_server:
  port: 80

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable Home Assistant API
api:
  password: !secret api_password
  
binary_sensor:
  - platform: gpio
    pin: D7
    name: "PIR Sensor"
    device_class: motion
    on_press:
      then:
        - light.turn_on: led
    on_release:
      then:
        - light.turn_off: led

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    id: led
    pin: GPIO3
    num_leds: 120
    name: "NeoPixel Light"
    color_correct: [70%, 70%, 70%]
    effects:
      - pulse:
      - random:
      - strobe:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
