esphome:
  name: fan
  friendly_name: esp
  name_add_mac_suffix: true

esp8266:
  board: nodemcuv2

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}
captive_portal:

web_server:
  port: 80
  version: 3

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

logger:
  level: DEBUG

fan:
  - platform: binary
    name: level1
    id: level1
    output: power1
    on_turn_on:
      then:
        - fan.turn_off: level2
        - fan.turn_off: level3
  - platform: binary
    name: level2
    id: level2
    output: power2
    on_turn_on:
      then:
        - fan.turn_off: level1
        - fan.turn_off: level3
  - platform: binary
    name: level3
    id: level3
    output: power3
    on_turn_on:
      then:
        - fan.turn_off: level1
        - fan.turn_off: level2

# output
output:
  - platform: gpio
    id: power1
    pin: GPIO16
  - platform: gpio
    id: power2
    pin: GPIO5
  - platform: gpio
    id: power3
    pin: GPIO4

# inputs
binary_sensor:
  - platform: gpio
    id: button1
    name: button1
    device_class: power
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        fan.turn_on: level1
    on_release:
      then:
        fan.turn_off: level1
  - platform: gpio
    id: button2
    name: button2
    device_class: power
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        fan.turn_on: level2
    on_release:
      then:
        fan.turn_off: level2
  - platform: gpio
    id: button3
    name: button3
    device_class: power
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        fan.turn_on: level3
    on_release:
      then:
        fan.turn_off: level3

i2c:
  sda: GPIO10
  scl: GPIO9
  scan: true

sensor:
  - platform: bmp280
    update_interval: 60s
    pressure:
      name: "Pressure"
      id: pressure
    temperature:
      name: "Temperature"
      id: temperature
#      on_value_range:
#      - below: 18
#        then:
#          - fan.turn_off: level1
#      - below: 20
#        then:
#          - fan.turn_on: level1
#      - above: 20
#        below: 22
#        then:
#          - fan.turn_on: level2
#          - fan.turn_off: level3
#      - above: 22
#        then:
#          - fan.turn_on: level3

display:
graph:
  - id: graph_temp
    duration: 168h
    width: 1024
    height: 768
    traces:
      - sensor: temperature
        continuous: true
      - sensor: pressure
        continuous: true
