esphome:
  name: sensor
  project:
    name: sensor.esphome
    version: "1.0"

esp8266:
  board: nodemcuv2

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

web_server:
  port: 80

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable Home Assistant API
api:
  password: !secret api_password

  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: sensor_mhz19

# connected hardware
as3935_i2c:
  irq_pin: GPIO12

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

display:
  - platform: ssd1306_i2c
    id: screen
    model: "SSD1306 128x32"
    address: 0x3C
    pages:
      - id: page1
        lambda: |-
          it.printf(5, 10, id(roboto), "Temp: %.1f °C", id(temperature).state);
      - id: page2
        lambda: |-
          it.printf(5, 10, id(roboto), "Co2: %.1f ppm", id(co2).state);
      - id: page3
        lambda: |-
          it.printf(5, 10, id(roboto), "Pressure: %.1f hPa", id(pressure).state);

interval:
  - interval: 10s
    then:
      - display.page.show_next: screen
      - component.update: screen

sensor:
  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
      id: value_energy
    distance:
      name: "Distance Storm"
      id: value_distance

  - platform: mhz19
    id: sensor_mhz19
    uart_id: com_uart
    co2:
      name: "CO2 Value"
      id: co2
    automatic_baseline_calibration: false

  - platform: bmp085
    temperature:
      id: temperature
      name: "Temperature"
    pressure:
      id: pressure
      name: "Pressure"
    update_interval: 59s

  - platform: adc
    pin: A0
    name: "Gas"
    id: gas
    update_interval: 53s
    unit_of_measurement: ""
    device_class: "gas"

binary_sensor:
  - platform: as3935
    name: "Storm Alert"

uart:
  - id: com_uart
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600

i2c:
  - id: com_i2c
    sda: GPIO4
    scl: GPIO5
    scan: true
